import "@/styles/globals.css";

import { type Metadata } from "next";
import { Urbanist } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseClientProvider } from "@/lib/supabase/provider";
import { QueryProvider } from "@/providers/client-query";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Urbanist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <QueryProvider>
      <SupabaseClientProvider>
        <html lang="en" className={`${geist.className}`}>
          <body>
            {children}
            <Toaster />
          </body>
        </html>
      </SupabaseClientProvider>
    </QueryProvider>
  );
}
