import "@/styles/globals.css";

import { type Metadata } from "next";
import { Urbanist } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseClientProvider } from "@/lib/supabase/provider";
import { QueryProvider } from "@/providers/client-query";
import { ModalProvider } from "@/providers/modal";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const urbanist = Urbanist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <QueryProvider>
      <SupabaseClientProvider>
        <html lang="en" className={`${urbanist.className}`}>
          <body>
            <ModalProvider>
              {children}
              <Toaster />
            </ModalProvider>
          </body>
        </html>
      </SupabaseClientProvider>
    </QueryProvider>
  );
}
